### ISSUE TITLE
hello Thank you, I am using the source code well.

### ISSUE THREAD

**Issue by six1773** [cmanley/PHP-Validate#6]
hello
Thank you, I am using the source code well.

Change string to number if string is number string  in file Validator.php : Mthod validate

error message
==> Parameter "score" failed validation "types" for string value "617"

I am not understand.
value 617 is integer However, it is recognized as a string

I'm Korean, so I can't speak English well. So please forgive me.

Thank you :)

**Comment by cmanley** [comment]
Hello,
You need to prove the bug with more information and a sample script so that I can reproduce it if it is really a bug.

**Comment by six1773** [comment]
This issue is not a bug. It's a convenience issue.

Your source code is great.

I want your library to recognize numeric strings as numbers.

I am using your source code modified.


my edit source code base on :cmanley/PHP-Validate:
![image](https://user-images.githubusercontent.com/98797538/201045829-6b5f4ca1-f2fc-4cc0-b8a4-74ce8a919f86.png)

![image](https://user-images.githubusercontent.com/98797538/201045959-0c2d6a36-3397-46b4-992c-0735da6ee838.png)


I hope your official fix.

I learned a lot from your source code. So thank you.

Thank you :)

**Comment by cmanley** [comment]
I'm not going to add a validation for types that look like they can be converted to other types. If you want to do those funky things then you can use the "callback", or "before" options.
